services:
  mysqldb:
    image: mysql:8.0
    container_name: tcg-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - tcg-db:/var/lib/mysql
    networks:
      - tcg-networks

  api:
    container_name: tcg-api
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    volumes:
      - ./src/uploads:/tcg-api/src/uploads
    environment:
      MYSQL_DB_HOST: mysqldb
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - tcg-networks

volumes:
  tcg-db:
    driver: local
    
networks:
  tcg-networks:
    driver: bridge